# Generated by Django 2.0.3 on 2018-03-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=16)),
                ('change', models.CharField(choices=[('created', 'created'), ('changed', 'changed'), ('removed', 'removed')], default='created', max_length=16)),
            ],
        ),
    ]
